[ants_logging]
enabled=True

[ants_metadata]
history=${CYLC_WORKFLOW_ID}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}

[ants_regridding_vertical]
scheme=Linear


[command]
default=ants-launch ancil_vertical_regrid.py \
       =${source} -o ${output} --ants-config ${ANTS_CONFIG} --target-${target_type} ${target} \
       =${begin} ${end}

[env]
ANTS_CONFIG=rose-app-run.conf
