[env]
output=/data/users/jennifer.hickson/ants_vertical_cli/ozone/$(ROSE_TASK_NAME)
source=/data/users/jennifer.hickson/ants_vertical_cli/ozone/Ozone_CMIP5_SPARCex_M1994-2005_N36L85_li-ch_G.nc
target=/data/users/jennifer.hickson/ants_vertical_cli/vertlevs_L70_50t_20s_80km
target_type=grid
